apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-tracker-app
  labels:
    app: weather-tracker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-tracker-app
  template:
    metadata:
      labels:
        app: weather-tracker-app
    spec:
      containers:
      - name: weather-tracker-app
        image: weathertracker:latest
        ports:
        - containerPort: 8000